### ISSUE TITLE
when inchling riding either another player or a mount appears flying 1 block above target

### ISSUE THREAD

**Issue by blakreaper** [MoriyaShiine/extra-origins#199] opened 2023-02-16 02:25 UTC
### Mod version

1.19.2

### A description of the issue

when my girlfriend an inchling tries to jockey me or ride a horse she appears flying 1 block above me or the mount i saw that it was supposely fixed but it keeps happening and both our mods are up to date

**Comment by MoriyaShiine** [comment] 2023-02-16 03:25
Fixed in 1.19-3, your mods aren't up to date; the fix is on Minecraft 1.19.3

**Closed by MoriyaShiine** 2023-02-16 03:25 UTC

**Comment by w4R1w** [comment] 2023-04-14 13:02
sorry for the necro, but me and my friends are playing on a 1.18.2 modpack, is there a fix for this version? I don't remember this issue being present in the previous versions. Maybe a specific older version would work?

**Comment by MoriyaShiine** [comment] 2023-04-14 14:14
I believe it was caused by a Pehkui update, so using an older version of that may work
