### ISSUE TITLE
Drinking Liquid Sunshine Crashes Game

### ISSUE THREAD

**Issue by berbaby** [MoriyaShiine/extra-origins#22] opened 2020-12-27 08:12 UTC
As a Floran, I made liquid sunlight and when I right clicked it, it crashed my game. I made my friend try it out too, and it crashed his game as well despite him being a Shulk. This is the crash report if it helps.

Description: Unexpected error
----------------------------------------------------------------------------------------------------------------------------------------------
java.lang.ClassCastException: net.minecraft.class_746 cannot be cast to net.minecraft.class_3222
	at net.minecraft.class_1812.handler$bfo000$getUseTime(class_1812.java:1045)
	at net.minecraft.class_1812.method_7881(class_1812.java)
	at moriyashiine.extraorigins.common.item.LiquidSunlightItem.method_7881(LiquidSunlightItem.java:50)
	at net.minecraft.class_1799.method_7935(class_1799.java:491)
	at net.minecraft.class_1309.method_6019(class_1309.java:2864)
	at net.minecraft.class_746.method_6019(class_746.java:528)
	at net.minecraft.class_5328.method_29282(class_5328.java:16)
	at net.minecraft.class_1812.method_7836(class_1812.java:81)
	at moriyashiine.extraorigins.common.item.LiquidSunlightItem.method_7836(LiquidSunlightItem.java:24)
	at net.minecraft.class_1799.method_7913(class_1799.java:239)
	at net.minecraft.class_636.method_2919(class_636.java:349)
	at net.optifine.override.PlayerControllerOF.method_2919(PlayerControllerOF.java:81)
	at net.minecraft.class_310.method_1583(class_310.java:1472)
	at net.minecraft.class_310.method_1508(class_310.java:1709)
	at net.minecraft.class_310.method_1574(class_310.java:1534)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/934275857.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1812.handler$bfo000$getUseTime(class_1812.java:1045)
	at net.minecraft.class_1812.method_7881(class_1812.java)
	at moriyashiine.extraorigins.common.item.LiquidSunlightItem.method_7881(LiquidSunlightItem.java:50)
	at net.minecraft.class_1799.method_7935(class_1799.java:491)
	at net.minecraft.class_1309.method_6019(class_1309.java:2864)
	at net.minecraft.class_746.method_6019(class_746.java:528)
	at net.minecraft.class_5328.method_29282(class_5328.java:16)
	at net.minecraft.class_1812.method_7836(class_1812.java:81)
	at moriyashiine.extraorigins.common.item.LiquidSunlightItem.method_7836(LiquidSunlightItem.java:24)
	at net.minecraft.class_1799.method_7913(class_1799.java:239)
	at net.minecraft.class_636.method_2919(class_636.java:349)
	at net.optifine.override.PlayerControllerOF.method_2919(PlayerControllerOF.java:81)
	at net.minecraft.class_310.method_1583(class_310.java:1472)
	at net.minecraft.class_310.method_1508(class_310.java:1709)

**Comment by MoriyaShiine** [comment] 2020-12-27 16:08
I can't reproduce this. What other mods do you have installed?

**Comment by berbaby** [comment] 2020-12-27 18:23
Here is a mod list:
----------------------------------------------------------------------------------------------------------------------------------------------
Gentle Fawn (by sakiraart)
Direbats (Fabric) (by andanteT)
Illuminations 🔥 (by doctor4t)
Fabric API (by asiekierka)
Mo' Structures (by ffrannny)
Origins: Classes (by Apace100)
Draylar's Battle Towers (by Draylar1)
Ancient Gateways (by openlyfay)
Better Graves (by Cerulan)
All The Blocks You Want (by azagwen)
Trinkets (Fabric) (by EmilyPloszaj)
Fabrication & Forgery (by unascribed)
Gravel Ores (Fabric) (by shedaniel)
Extra Origins (by MoriyaShiine)
OptiFabric (by modmuss50)
Industrial Revolution (by GabrielHOlv)
Allure (by purple_steve)
Bedspreads (Fabric) (by TheIllusiveC4)
Edit Sign (by RakSrinaNa)
Auth Me (by Ax1eum)
Jumploader (by comp500)
RPGStats (by TheoreticallyUseful)
StuffZ (by Globox_Z)
Anti Auto Jump (by attballpark)
Adorn (by Juicebus)
Monster Of The Ocean Depths[FABRIC] (by dinohunter0727)
Patchouli (Fabric) (by williewillus)
Staff of Building (by Draylar1)
Eldritch Mobs (by cyborg_pigeon)
Cardinal Components (by UpcraftLP)
Glassential (Fabric) (by Lykrast)
Straw Dummy (by GabrielHOlv)
Blockus (by Brandcraft_)
YUNG's Better Caves (Fabric) (by YUNGNICKYOUNG)
FallingTree (by RakSrinaNa)
Dark Loading Screen (by Neecko5b84)
The Bumblezone (Fabric) (by telepathicgrunt)
Better Dropped Items (by Draylar1)
Flesh 2 Leather [FABRIC] (by CodenameRevy)
Door Knocker (by FroyoCS)
Roughly Enough Items Fabric (REI) (by shedaniel)
Mouse Wheelie (Fabric) (by Siphalor)
Campanion (by wyn_price)
VoxelMap (by MamiyaOtaru)
Art of Alchemy: Memoriam (by CumulusMC)
Repurposed Structures (Fabric) (by telepathicgrunt)
BackSlot (by Globox_Z)
Mini Extras [Fabric] (by iamshift_)
Blur (Fabric) (by Motschen)
YUNG's API (Fabric) (by YUNGNICKYOUNG)
Artifacts (Fabric) (by florensie)
Extra Bows (by MrMarnic)
Villager Hats (by Lemonszz)
Terrestria (by coderbot)
Fabric Language Kotlin (by modmuss50)
Netherite Plus (by OroArmor)
Pehkui (by Virtuoel)
BetterNether (by paulevs)
Traverse (by ProspectorDev)
Dynamic FPS (by juliand665)
Flamingo, oh, oh, oh... (by sakiraart)
CC: Restitched (by Zundrel)
Origins (by Apace100)
Improved Stations (Fabric) (by shedaniel)
MedievalWeapons (by Globox_Z)
Glow Squid and more! (by cactusduper)
YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
BetterEnd (by paulevs)
AdventureZ (by Globox_Z)
AppleSkin (by squeek502)
[FABRIC] GeckoLib (by ThanosGecko)
MC Dungeons Armors (by chronos_sacaria)

**Comment by CammiePone** [comment] 2020-12-27 19:32
So I just tested on a dedicated server as well, and was unable to reproduce the issue with just Extra Origins and its dependencies installed. Whatever is causing the issue, it's not Extra Origins. My best guesses would be anything that messes with food, whether that be as an item, or as a whole mechanic. If any stick out, try removing them and reproducing the crash.

**Comment by MoriyaShiine** [comment] 2021-02-14 21:53
Haven't had a response in over a month so closing this

**Closed by MoriyaShiine** 2021-02-14 21:53 UTC
